# --- Debounce Settings ---
# Default: 5ms
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
# Default: 5ms
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Enable mouse emulation.
CONFIG_ZMK_POINTING=y

# Change idle settings
# Default: 300000 (5 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=300000

# Deep sleep settings
CONFIG_ZMK_SLEEP=y
# Default: 900000 (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"
